const CRYPSIDE_ROOT = '/home/idona/MoStar/_apps/financial/crypside/CrypSide';
const OBSERVER_DIR = `${CRYPSIDE_ROOT}/observer_bundle`;
const PYTHON_BIN = `${CRYPSIDE_ROOT}/.venv/bin/python3.12`;
const ENV_FILE = `${CRYPSIDE_ROOT}/.env`;
const PM2_LOG_DIR = `${CRYPSIDE_ROOT}/logs/pm2`;

module.exports = {
  apps: [
    {
      name: 'crypside-api',
      cwd: '/home/idona/MoStar/_apps/financial/crypside/CrypSide',
      script: '/home/idona/MoStar/_apps/financial/crypside/CrypSide/.venv/bin/python3.12',
      args: '-m uvicorn api:app --host 127.0.0.1 --port 8787',
      interpreter: 'none',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        PYTHONUNBUFFERED: '1',
        PORT: '8787',
      },
    },
    {
      name: 'crypside-scanner',
      cwd: OBSERVER_DIR,
      script: PYTHON_BIN,
      args: 'scanner.py',
      interpreter: 'none',
      env_file: ENV_FILE,
      env: {
        PYTHONUNBUFFERED: '1',
      },
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: true,
      out_file: `${PM2_LOG_DIR}/crypside-scanner-out.log`,
      error_file: `${PM2_LOG_DIR}/crypside-scanner-error.log`,
    },
    {
      name: 'crypside-outcome-tracker',
      cwd: OBSERVER_DIR,
      script: PYTHON_BIN,
      args: 'outcome_tracker.py --loop',
      interpreter: 'none',
      env_file: ENV_FILE,
      env: {
        PYTHONUNBUFFERED: '1',
      },
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: true,
      out_file: `${PM2_LOG_DIR}/crypside-outcome-tracker-out.log`,
      error_file: `${PM2_LOG_DIR}/crypside-outcome-tracker-error.log`,
    },
    {
      name: 'crypside-funding-collector',
      cwd: OBSERVER_DIR,
      script: PYTHON_BIN,
      args: 'funding_collector.py',
      interpreter: 'none',
      env_file: ENV_FILE,
      env: {
        PYTHONUNBUFFERED: '1',
      },
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: true,
      out_file: `${PM2_LOG_DIR}/crypside-funding-collector-out.log`,
      error_file: `${PM2_LOG_DIR}/crypside-funding-collector-error.log`,
    },
    {
      name: 'crypside-oi-collector',
      cwd: OBSERVER_DIR,
      script: PYTHON_BIN,
      args: 'oi_collector.py',
      interpreter: 'none',
      env_file: ENV_FILE,
      env: {
        PYTHONUNBUFFERED: '1',
      },
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: true,
      out_file: `${PM2_LOG_DIR}/crypside-oi-collector-out.log`,
      error_file: `${PM2_LOG_DIR}/crypside-oi-collector-error.log`,
    },
    {
      name: 'crypside-ls-ratio-collector',
      cwd: OBSERVER_DIR,
      script: PYTHON_BIN,
      args: 'ls_ratio_collector.py',
      interpreter: 'none',
      env_file: ENV_FILE,
      env: {
        PYTHONUNBUFFERED: '1',
      },
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: true,
      out_file: `${PM2_LOG_DIR}/crypside-ls-ratio-collector-out.log`,
      error_file: `${PM2_LOG_DIR}/crypside-ls-ratio-collector-error.log`,
    },
    {
      name: 'crypside-frontend',
      cwd: CRYPSIDE_ROOT,
      script: 'npm',
      args: 'run start -- --hostname 127.0.0.1 --port 3001',
      interpreter: 'none',
      env_file: ENV_FILE,
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
        NEXT_PUBLIC_API_BASE_URL: 'http://127.0.0.1:8787',
        NEXT_PUBLIC_API_WS_URL: 'ws://127.0.0.1:8787/ws',
      },
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: true,
      out_file: `${PM2_LOG_DIR}/crypside-frontend-out.log`,
      error_file: `${PM2_LOG_DIR}/crypside-frontend-error.log`,
    },
    {
      name: 'moedge-sentinel',
      cwd: OBSERVER_DIR,
      script: PYTHON_BIN,
      args: 'moedge_sentinel.py',
      interpreter: 'none',
      env_file: ENV_FILE,
      env: {
        PYTHONUNBUFFERED: '1',
        MOEDGE_SENTINEL_PORT: '3010',
        MOEDGE_SENTINEL_INTERVAL: '1800',
      },
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      time: true,
      out_file: `${PM2_LOG_DIR}/moedge-sentinel-out.log`,
      error_file: `${PM2_LOG_DIR}/moedge-sentinel-error.log`,
    },
  ],
};
